spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
